# Monokai-Charcoal Colorsheme
[colors.primary]
background = '#1a1a1a'
foreground = '#FFFFFF'

[colors.normal]
black =   '#1a1a1a'
red =     '#f4005f'
green =   '#98e024'
yellow =  '#fa8419'
blue =    '#9d65ff'
magenta = '#f4005f'
cyan =    '#58d1eb'
white =   '#c4c5b5'

[colors.bright]
black =   '#625e4c'
red =     '#f4005f'
green =   '#98e024'
yellow =  '#e0d561'
blue =    '#9d65ff'
magenta = '#f4005f'
cyan =    '#58d1eb'
white =   '#f6f6ef'

[window]
title = "Alacritty"
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
style = "Regular"

[cursor]
style = "Beam"
