# Modified Monokai-Charcoal Colorsheme
[colors.primary]
background = '#232326'
foreground = '#FFFFFF'

[colors.normal]
black =   '#1a1a1a'
red =     '#f4005f'
green =   '#98e024'
yellow =  '#fa8419'
blue =    '#9d65ff'
magenta = '#f4005f'
cyan =    '#58d1eb'
white =   '#c4c5b5'

[colors.bright]
black =   '#625e4c'
red =     '#f4005f'
green =   '#98e024'
yellow =  '#e0d561'
blue =    '#9d65ff'
magenta = '#f4005f'
cyan =    '#58d1eb'
white =   '#f6f6ef'

[window]
title = "Alacritty"
opacity = 1.0

[window.padding]
x = 0
y = 0

[font]
size = 12

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Light Italic" 

[cursor.style]
shape = "Beam"
blinking = "Always"
